// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "gui.h"

void GUI::cb_DBG_i(Fl_Button*, void*) {
  DBG_cb();
}
void GUI::cb_DBG(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_DBG_i(o,v);
}

void GUI::cb_NewB_i(Fl_Button*, void*) {
  NewB_cb();
}
void GUI::cb_NewB(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_NewB_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(265, 290, "GUI");
    uiw->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(15, 15, 225, 40, "DBG");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_DBG);
    } // Fl_Button* o
    { NewB = new Fl_Button(15, 225, 115, 55, "NewB");
      NewB->color((Fl_Color)61);
      NewB->selection_color((Fl_Color)89);
      NewB->labelsize(34);
      NewB->callback((Fl_Callback*)cb_NewB);
    } // Fl_Button* NewB
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::NewB_cb() {
  scene->NewB();
}
